import {
  FaReact,
  FaSass,
  FaGitAlt,
  FaNodeJs,
  FaGithub,
  FaFigma,
} from 'react-icons/fa';
import {
  SiAdobexd,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobepremierepro,
  SiTypescript,
  SiJavascript,
  SiCss3,
  SiHtml5,
} from 'react-icons/si';

export const techStack = [
  {
    techName: 'React.JS',
    techIcon: FaReact,
    link: '',
    color: '#61DAFB',
    stroke: 'brown',
  },
  {
    techName: 'TypeScript',
    techIcon: SiTypescript,
    link: '',
    color: '#3178C6',
    stroke: 'brown',
  },
  {
    techName: 'JavaScript',
    techIcon: SiJavascript,
    link: '',
    color: '#F7DF1E',
    stroke: 'brown',
  },
  {
    techName: 'HTML',
    techIcon: SiHtml5,
    link: '',
    color: '#E34F26',
    stroke: 'brown',
  },
  {
    techName: 'CSS',
    techIcon: SiCss3,
    link: '',
    color: '#1572B6',
    stroke: 'brown',
  },
  {
    techName: 'SASS',
    techIcon: FaSass,
    link: '',
    color: '#CC6699',
    stroke: 'brown',
  },
  {
    techName: 'Node.JS',
    techIcon: FaNodeJs,
    link: '',
    color: '#339933',
    stroke: 'brown',
  },
  {
    techName: 'GitHub',
    techIcon: FaGithub,
    link: '',
    color: '#181717',
    stroke: 'brown',
  },
  {
    techName: 'XD',
    techIcon: SiAdobexd,
    link: '',
    color: '#FF61F6',
    stroke: 'brown',
  },
  {
    techName: 'Photoshop',
    techIcon: SiAdobephotoshop,
    link: '',
    color: '#31A8FF',
    stroke: 'brown',
  },
  {
    techName: 'Illustrator',
    techIcon: SiAdobeillustrator,
    link: '',
    color: '#FF9A00',
    stroke: 'brown',
  },
  {
    techName: 'Premiere Pro',
    techIcon: SiAdobepremierepro,
    link: '',
    color: '#9999FF',
    stroke: 'brown',
  },
  {
    techName: 'Figma',
    techIcon: FaFigma,
    link: '',
    color: '#F24E1E',
    stroke: 'brown',
  },
];
